### PR TITLE
CCXDEV-5093 aggregate backend support for the new /rating endpoint 

### PR DESCRIPTION
**Pull request by joselsegura**
# Description

This change intends to add the needed tables into the database, along with endpoint changes to allow to aggregator's clients (smart-proxy) to store the "ratings" for rules from a given user in the Advisor frontend

Fixes CCXDEV-5093

## Type of change
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update
- Unit tests (no changes in the code)
- REST API tests
- Documentation update

## Testing steps

Regular CI

## Checklist
* [x] `make before_commit` passes
* [x] updated documentation wherever necessary
* [x] added or modified tests if necessary
* [x] updated schemas and validators in [insights-data-schemas](https://github.com/RedHatInsights/insights-data-schemas) in case of input/output change

### CODE REVIEW

**Comment by tisnik** [comment]
IMHO we might need to get the data per org, so probably worth to add an `org_id` column there?

**Comment by joselsegura** [comment]
> IMHO we might need to get the data per org, so probably worth to add an `org_id` column there?

Good idea, added.
I'm starting to think that some info that we have in the DB should be split in "utility tables", like "users" that contains user_id and org_id, or rule_error_keys, that creates an unique selector for pairs rule+error_key. Now we have the same info in tons of rows of the database in different tables!

**Review by Bee-lee — COMMENTED** [review]
looks fine so far

**Review by dpensi — APPROVED** [review]

**Review by Bee-lee — APPROVED** [review]
LGTM

**Review by tisnik — APPROVED** [review]
LGTM

**Pull request merged**
