### PR TITLE
fixed bug with multiple streams

### LINKED ISSUE #609: Log stream not found when there are multiple stream starting with the same prefix

### PR DESCRIPTION
**Pull request by Sergey1011010**
# Description

The fix is here https://github.com/Sergey1011010/ejholmes-cloudwatch/commit/0f116106424878ea2ff6d15bf33864d4d5859234

Fixes #609

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Testing steps

`make before_commit`

### CODE REVIEW

**Comment by Sergey1011010** [comment]
@tisnik the first fork of original repo fixes the issue with writing to existing stream, the second fork of fork(mine) fixes the bug when there are multiple streams with the same prefix ("stream", "stream1", "stream2", etc)

**Comment by tisnik** [comment]
> @tisnik the first fork of original repo fixes the issue with writing to existing stream, the second fork of fork(mine) fixes the bug when there are multiple streams with the same prefix ("stream", "stream1", "stream2", etc)

I know, but I'm a bit worried who/when will sync with upstream. We will be asked during security review. Is not it better to simply create PR?

**Comment by Sergey1011010** [comment]
@tisnik original repo didn't merge the fix and I was unable to make PR with my changes to the first fork (see https://github.com/ejholmes/cloudwatch/pull/9).

**Comment by tisnik** [comment]
> @tisnik original repo didn't merge the fix and I was unable to make PR with my changes to the first fork (see [ejholmes/cloudwatch#9](https://github.com/ejholmes/cloudwatch/pull/9)).

Hmm I see. Then please do me a favor and use https://github.com/RedHatInsights/cloudwatch which will look like a bit more "official". TY so much!

**Comment by Sergey1011010** [comment]
@tisnik fixed

**Comment by discobean** [comment]
@Sergey1011010 glad my code helps :)

**Pull request merged**
