### PR TITLE
Retrieve column from DB and add to the response

### PR DESCRIPTION
**Pull request by joselsegura**
# Description

Retrieve the rule hits count from the database column and add it to the API response

Fixes #CCXDEV-12525

## Type of change

- New feature (non-breaking change which adds functionality)

## Testing steps

Not tested yet

## Checklist
* [ ] `make before_commit` passes
* [ ] updated documentation wherever necessary
* [ ] added or modified tests if necessary
* [ ] updated schemas and validators in [insights-data-schemas](https://github.com/RedHatInsights/insights-data-schemas) in case of input/output change

### CODE REVIEW

**Review by JiriPapousek — APPROVED** [review]

**Comment by Bee-lee** [comment]
@joselsegura could you pls add some real values to the UTs?

**Review by epapbak — APPROVED** [review]

**Pull request merged**
