### PR TITLE
Fix aggregator page

### PR DESCRIPTION
**Pull request by joselsegura**
# Description

Trying to fix the problems in GH page for this repository

## Type of change

- Documentation update

## Testing steps

Let the CI fix it

## Checklist
* [ ] `make before_commit` passes
* [ ] updated documentation wherever necessary
* [ ] added or modified tests if necessary
* [ ] updated schemas and validators in [insights-data-schemas](https://github.com/RedHatInsights/insights-data-schemas) in case of input/output change

### CODE REVIEW

**Review by tisnik — APPROVED** [review]
Let's try it!

**Review by JiriPapousek — APPROVED** [review]

**Pull request merged**
