### PR TITLE
Add BDD tests stage in CI

### PR DESCRIPTION
**Pull request by epapbak**
# Description

Add new stage for running BDD tests as part of the PR verification

## Type of change

New step in CI pipeline

## Testing steps

CI

## Checklist
* [ ] `make before_commit` passes
* [ ] updated documentation wherever necessary
* [ ] added or modified tests if necessary
* [ ] updated schemas and validators in [insights-data-schemas](https://github.com/RedHatInsights/insights-data-schemas) in case of input/output change

### CODE REVIEW

**Review by tisnik — APPROVED** [review]
ok

**Comment by juandspy** [comment]
iqe failing a lot :/

**Comment by epapbak** [comment]
> 

But I don't know why, TBH...

**Review by Bee-lee — APPROVED** [review]

**Pull request merged**
