### PR TITLE
[CCXDEV-12623] display_name added to objects/workloads list

### PR DESCRIPTION
**Pull request by Jakub007d**
# Description

Adding new field named `display_name` into a list of objects hitting each rule to be used in UI that is already expecting this attribute.

Fixes # [(issue)](https://issues.redhat.com/browse/CCXDEV-12623)

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)
- Changes in REST API schema

## Testing steps
Tested in ephemeral

## Checklist
* [ ] `make before_commit` passes
* [ ] updated documentation wherever necessary
* [ ] added or modified tests if necessary
* [ ] updated schemas and validators in [insights-data-schemas](https://github.com/RedHatInsights/insights-data-schemas) in case of input/output change

### CODE REVIEW

**Review by epapbak — APPROVED** [review]

**Review by epapbak — DISMISSED** [review]
I approved too fast. This might affect the API specification. Please verify that and update if needed

**Review by epapbak — APPROVED** [review]

**Review by matysek — APPROVED** [review]
/lgtm

**Pull request merged**
